version: '3'
services:
  db:
    image: mysql:5.6
    container_name: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - "./mysql-sio/${COMPOSE_PROJECT_NAME}:/var/lib/mysql"
      - "./sql:/docker-entrypoint-initdb.d:ro"
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    env_file: .env
    environment:
      - MYSQL_PORT
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
